### ISSUE TITLE
Evaluate Mailgun as mail service provider

### ISSUE THREAD

**Issue by arouault** [MAPC/youth-match-v2#147]
Re-evaluate mailgun as mail provider. Look at sendgrid and/or Mandril

**Comment by mzagaja** [comment]
I am not sure the issue is MailGun specifically or something else. MailGun has an [interesting article](https://documentation.mailgun.com/en/latest/best_practices.html#email-best-practices) on deliverability.  I think the issue here is we don't really have much data to actually diagnose this problem. Going forward we can test email spam scores using http://www.mail-tester.com/ before sending emails to the public.
