### ISSUE TITLE
Re-Import Data from Deron with Accurate Data

### ISSUE THREAD

**Issue by arouault** [MAPC/youth-match-v2#72]
Reimport data from Deron on Partner sites, emails, and allocations from this spreadsheet: 

https://docs.google.com/spreadsheets/d/1zRsnZS0Ut5ew4SOUypNp3btQrIvCmaleXu_AV45DFiA/edit?usp=sharing

**Comment by mzagaja** [comment]
I talked with Deron and there are some large points of confusion here:

1. We originally received a Google app thing that was somehow combined with position data from an unknown place to become the thing in the CartoDB map at https://mapc.carto.com/u/mapc-admin/tables/job_descriptions_address/public?redirected=true. Talking to Deron it turns out that Google map referred not to positions but to locations. 

2. The position count from the canonical list above was significantly larger than the list from the CartoDB map. It was also larger than the number of sites in the KML file (169 according to @allthesignals). This was a red flag to me and so it appears that the CartoDB map is missing data on positions and/or partners.

Deron is going to update the Google map to make sure it has the latest information on partner sites. But if we're going to use the list of partner sites from the Google map then we need to allow job sites to have multiple interest categories to correspond with what we have in our app. We also cannot use the ideal candidate or qualifications information because they will differ based on the job.
